name: Deploy product-manager-backend to GCP

on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/product-manager-backend:latest
      
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2
      
      # Login to GCP
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with: 
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
        
      # Gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
      
      # Build image
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .
      
      # Push image to registry
      - name: Push Docker Image
        run: docker push $IMAGE_NAME
      
      # Deploy image
      - name: Deploy Docker Image
        run: gcloud run deploy product-manager-backend --image $IMAGE_NAME --region southamerica-east1 --memory 512Mi --min-instances 1 --max-instances 5 --platform managed --port 8080 --allow-unauthenticated
