name: Deploy product-manager-backend to GCP

on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    name: Build and Deploy to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: anserjufe-319714

      - name: Setup Docker Authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: docker build -t southamerica-east1-docker.pkg.dev/anserjufe-319714/docker-repo/product-manager-backend:latest .
    
      - name: Push Docker Image to Artifact Registry
        run: docker push southamerica-east1-docker.pkg.dev/anserjufe-319714/docker-repo/product-manager-backend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy product-manager-backend \
            --image southamerica-east1-docker.pkg.dev/anserjufe-319714/docker-repo/product-manager-backend:latest \
            --region southamerica-east1 \
            --memory 512Mi \
            --min-instances 1 \
            --max-instances 5 \
            --platform managed \
            --port 8080 \
            --allow-unauthenticated
